name: Validar PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  hugo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Validar build do Hugo
        run: hugo --gc --minify --baseURL "https://example.com/"

      - name: Verificar que a geração foi concluída
        run: test -f public/index.html
